general:
  world_frame: "map"
  logging_level: debug
  allow_reset_map_service: true

map:
  type: hashed_wavelet_octree
  min_cell_width: { meters: 0.03 }

map_operations:
  - type: threshold_map
    once_every: { seconds: 2.0 }
  - type: prune_map
    once_every: { seconds: 10.0 }
  - type: publish_map
    once_every: { seconds: 2.0 }

measurement_integrators:
  depth_camera_front_upper_short_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 0.3 }
      max_range: { meters: 1.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.03 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 428.0040283203125
      fy: 428.0040283203125
      cx: 429.46905517578125
      cy: 233.146240234375
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.005 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_front_upper_medium_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 8.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.06 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 428.0040283203125
      fy: 428.0040283203125
      cx: 429.46905517578125
      cy: 233.146240234375
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.03 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_rear_upper_short_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 0.3 }
      max_range: { meters: 1.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.03 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 427.3077392578125
      fy: 427.3077392578125
      cx: 426.9342956542969
      cy: 233.3394012451172
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.005 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_rear_upper_medium_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 8.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.06 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 427.3077392578125
      fy: 427.3077392578125
      cx: 426.9342956542969
      cy: 233.3394012451172
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.03 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_left_short_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 0.5 }
      max_range: { meters: 1.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.03 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 427.0599060058594
      fy: 427.0599060058594
      cx: 423.9487609863281
      cy: 230.01365661621094
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.005 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_left_medium_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 3.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.06 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 427.0599060058594
      fy: 427.0599060058594
      cx: 423.9487609863281
      cy: 230.01365661621094
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.03 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_right_short_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 0.5 }
      max_range: { meters: 1.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.03 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 428.760009765625
      fy: 428.760009765625
      cx: 425.7598571777344
      cy: 232.03164672851562
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.005 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_right_medium_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 3.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.06 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 428.760009765625
      fy: 428.760009765625
      cx: 425.7598571777344
      cy: 232.03164672851562
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.03 }
      scaling_free: 0.2
      scaling_occupied: 0.4

inputs:
  - type: depth_image_topic
    topic_name: "/depth_camera_front_upper/aligned_depth_to_infra1/image_masked"
    depth_scale_factor: 0.001
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }
    time_offset: { seconds: -0.025 }
    measurement_integrator_names:
      - depth_camera_front_upper_short_range
      - depth_camera_front_upper_medium_range

  - type: depth_image_topic
    topic_name: "/depth_camera_rear_upper/aligned_depth_to_infra1/image_masked"
    depth_scale_factor: 0.001
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }
    time_offset: { seconds: -0.025 }
    measurement_integrator_names:
      - depth_camera_rear_upper_short_range
      - depth_camera_rear_upper_medium_range

  - type: depth_image_topic
    topic_name: "/depth_camera_left/aligned_depth_to_infra1/image_masked"
    depth_scale_factor: 0.001
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }
    time_offset: { seconds: -0.025 }
    measurement_integrator_names:
      - depth_camera_left_short_range
      - depth_camera_left_medium_range

  - type: depth_image_topic
    topic_name: "/depth_camera_right/aligned_depth_to_infra1/image_masked"
    depth_scale_factor: 0.001
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }
    time_offset: { seconds: -0.025 }
    measurement_integrator_names:
      - depth_camera_right_short_range
      - depth_camera_right_medium_range
