general:
  world_frame: "odom"
  logging_level: debug
  allow_reset_map_service: true

map:
  type: hashed_wavelet_octree
  min_cell_width: { meters: 0.03 }

map_operations:
  - type: threshold_map
    once_every: { seconds: 2.0 }
  - type: prune_map
    once_every: { seconds: 10.0 }
  - type: publish_map
    once_every: { seconds: 2.0 }

measurement_integrators:
  depth_camera_front_lower_short_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 0.3 }
      max_range: { meters: 1.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.03 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 427.0570373535156
      fy: 427.0570373535156
      cx: 407.53546142578125
      cy: 236.9319305419922
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.005 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_front_lower_medium_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 6.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.06 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 427.0570373535156
      fy: 427.0570373535156
      cx: 407.53546142578125
      cy: 236.9319305419922
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.03 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_front_upper_short_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 0.3 }
      max_range: { meters: 1.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.03 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 424.9310302734375
      fy: 424.9310302734375
      cx: 425.49896240234375
      cy: 240.00094604492188
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.005 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_front_upper_medium_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 6.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.06 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 424.9310302734375
      fy: 424.9310302734375
      cx: 425.49896240234375
      cy: 240.00094604492188
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.03 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_rear_lower_short_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 0.3 }
      max_range: { meters: 1.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.03 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 418.2395935058594
      fy: 418.2395935058594
      cx: 419.311767578125
      cy: 241.22569274902344
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.005 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_rear_lower_medium_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 6.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.06 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 418.2395935058594
      fy: 418.2395935058594
      cx: 419.311767578125
      cy: 241.22569274902344
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.03 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_rear_upper_short_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 0.3 }
      max_range: { meters: 1.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.03 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 419.66302490234375
      fy: 419.66302490234375
      cx: 425.7276611328125
      cy: 238.27206420898438
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.005 }
      scaling_free: 0.2
      scaling_occupied: 0.4

  depth_camera_rear_upper_medium_range:
    integration_method:
      type: hashed_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 6.0 }
      termination_update_error: 0.1
      max_update_resolution: { meters: 0.06 }
    projection_model:
      type: pinhole_camera_projector
      width: 848
      height: 480
      fx: 419.66302490234375
      fy: 419.66302490234375
      cx: 425.7276611328125
      cy: 238.27206420898438
    measurement_model:
      type: continuous_ray
      range_sigma: { meters: 0.03 }
      scaling_free: 0.2
      scaling_occupied: 0.4

inputs:
  - type: depth_image_topic
    topic_name: "/depth_camera_front_lower/depth/image_rect_raw"
    depth_scale_factor: 0.001
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }
    time_offset: { seconds: -0.025 }
    measurement_integrator_names:
      - depth_camera_front_lower_short_range
      - depth_camera_front_lower_medium_range

  - type: depth_image_topic
    topic_name: "/depth_camera_front_upper/depth/image_rect_raw"
    depth_scale_factor: 0.001
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }
    time_offset: { seconds: -0.025 }
    measurement_integrator_names:
      - depth_camera_front_upper_short_range
      - depth_camera_front_upper_medium_range

  - type: depth_image_topic
    topic_name: "/depth_camera_rear_lower/depth/image_rect_raw"
    depth_scale_factor: 0.001
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }
    time_offset: { seconds: -0.025 }
    measurement_integrator_names:
      - depth_camera_rear_lower_short_range
      - depth_camera_rear_lower_medium_range

  - type: depth_image_topic
    topic_name: "/depth_camera_rear_upper/depth/image_rect_raw"
    depth_scale_factor: 0.001
    topic_queue_length: 1
    max_wait_for_pose: { seconds: 1.0 }
    time_offset: { seconds: -0.025 }
    measurement_integrator_names:
      - depth_camera_rear_upper_short_range
      - depth_camera_rear_upper_medium_range
